/**
 * Public technical-SEO endpoints (Phase 3A): /sitemap.xml and /robots.txt.
 *
 * These are the crawl-contract files search engines and AI search systems
 * fetch to discover, understand and index the public Verito website. The
 * assets are generated by the pure SEO engines (engine/sitemap.ts and
 * engine/robots.ts) from the single SEO_CONFIG registry — nothing is
 * hardcoded here, so public/private route changes flow through automatically.
 *
 *   GET /sitemap.xml — indexable public pages only (never private routes)
 *   GET /robots.txt  — allow public pages, disallow private app + /internal
 *
 * Both endpoints are anonymous and safe: they only emit route-registry-derived
 * assets and never touch seller data, credentials, auth, or payment data.
 * A short public cache (1h) keeps crawler fetch costs down; the assets are
 * regenerated from config on every request, so route changes go live within
 * the cache window.
 */

import { httpAction } from "../_generated/server";
import { buildSitemapXml } from "./engine/sitemap";
import { buildRobotsTxt } from "./engine/robots";
import { getSiteUrl } from "./engine/config";

function text(body: string, contentType: string): Response {
  return new Response(body, {
    headers: {
      "Content-Type": contentType,
      "Cache-Control": "public, max-age=3600",
    },
  });
}

export const sitemapXml = httpAction(async () => {
  const siteUrl = getSiteUrl(process.env as Record<string, string | undefined>);
  return text(buildSitemapXml({ siteUrl }), "application/xml; charset=utf-8");
});

export const robotsTxt = httpAction(async () => {
  const siteUrl = getSiteUrl(process.env as Record<string, string | undefined>);
  return text(buildRobotsTxt({ siteUrl }), "text/plain; charset=utf-8");
});
